### ISSUE TITLE
Check if pak is already installed when running groupInstall(), rather than forcing / not forcing

### ISSUE THREAD

**Issue by jsirianni** [BlueMedoraPublic/vropscli#41]
Currently `groupInstall()` will attempt to upload and install all MPs. We can a utilize the `force` flags to either force install or skip, however, I think it would be more elegant to check if the solution already exists before attempting to do anything. This would allow groupInstall() to behave almost like configuration management.

**Comment by rpocklington** [comment]
I'm specifically implementing that an attempt to upload an exact match for an already installed pak will cause that pak to be skipped.

The following existing behavior will be preserved:

> If a pak file is already installed, but the pak file to be uploaded is a higher-numbered version, then the installed pak will be overwritten by the one being uploaded _even if force_install is set to false_
