### ISSUE TITLE
Generic error when providing a path to a file using installPak command

### ISSUE THREAD

**Issue by jhowellbm** [BlueMedoraPublic/vropscli#88]
Seeing the following error, when accidentally navigating to a path using the installPak command:

(vropscli) bash-4.4$ ./vropscli.py installPak ~/Desktop/IBMHMC-6.3_1.0.0_b20180904.164343.pak
Error: Expecting value: line 1 column 1 (char 0)
Pass the -v flag for more verbose error messages

Note, the user isn't supposed to enter a path here (they're supposed to provide the ID of an uploaded pak file).   But let's provide a more informative error message here, in the event another user makes the same mistake.

**Comment by vignesh97** [comment]
#112 - PR

**Comment by ssmiller25** [comment]
Fixed as part of #112
